---
abstract: 'Extract the main content of a web page'
author:
  - 'Anirvan Chatterjee <anirvan@cpan.org>'
build_requires:
  File::Slurp: 9999.12
  HTML::FormatText: 2.04
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
keywords:
  - readability
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ExtractMain
provides:
  HTML::ExtractMain:
    file: lib/HTML/ExtractMain.pm
    version: 0.61
requires:
  Carp: 0
  HTML::TreeBuilder: 3.23
  Object::Destroyer: 2
  Scalar::Util: 1.18
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/anirvan/html-extractmain
version: 0.61
